### PR TITLE
Added new managed config rules

### PR DESCRIPTION
**Pull request by duraikkannuv2**

### CODE REVIEW

**Comment by grothja** [comment]
Thanks @duraikkannuv2; was the `generate-rule-pack-info.rb` script run to see new/updated rule pack info?

**Comment by duraikkannuv2** [comment]
> Thanks @duraikkannuv2; was the `generate-rule-pack-info.rb` script run to see new/updated rule pack info?

No, I didn't run it. I ran the `discover-new-rules.rb` script to get the new rule list. Should I run the generate-rule-pack-info.rb?

**Comment by grothja** [comment]
Yes, that would be great.  It should just update the rule pack YAML files, so nothing else is needed after that.

**Review by grothja — APPROVED** [review]
LGTM

**Pull request merged**
